title: A Life of Coding
author: Aaron J.
email: Jonesa7667@gmail.com
description: This is my journey into coding. Hope you enjoy!

#SM
twitter_username: APJ7667
github_username:  fatbuffdude

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
